name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
      - run: docker build -t dantasaf/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true dantasaf/react-test npm test

      - run: docker build -t dantasaf/multi-client ./client
      - run: docker build -t dantasaf/multi-nginx ./nginx
      - run: docker build -t dantasaf/multi-server ./server
      - run: docker build -t dantasaf/multi-worker ./worker

      - run: docker push dantasaf/multi-client
      - run: docker push dantasaf/multi-nginx
      - run: docker push dantasaf/multi-server
      - run: docker push dantasaf/multi-worker
