name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
      - run: docker build -t dantasaf/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true dantasaf/react-test npm test
